_wandb:
    value:
        cli_version: 0.22.2
        e:
            rnvgpbze82qvfas9wy9q4f3u0jkrbccr:
                codePath: src\models\train_model.py
                codePathLocal: src\models\train_model.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "8001299673088"
                        used: "629094105088"
                email: tzsolutionsbusiness@gmail.com
                executable: D:\AI_PROJECTS\alpha-factory\venv\Scripts\python.exe
                git:
                    commit: 20e42df8dd89997380988daeb4d9f9a6f66afaf2
                    remote: https://github.com/TheNetworktz/alpha-factory.git
                gpu: NVIDIA GeForce RTX 3090 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 3090 Ti
                      uuid: GPU-eca7ce5e-8e7f-2981-3779-7f0a6661a2a8
                host: DESKTOP-CFH1CQT
                memory:
                    total: "274711601152"
                os: Windows-11-10.0.26100-SP0
                program: D:\AI_PROJECTS\alpha-factory\src\models\train_model.py
                python: CPython 3.13.7
                root: D:\AI_PROJECTS\alpha-factory
                startedAt: "2025-10-20T19:27:53.386366Z"
                writerId: rnvgpbze82qvfas9wy9q4f3u0jkrbccr
        m: []
        python_version: 3.13.7
        t:
            "3":
                - 2
                - 19
            "4": 3.13.7
            "5": 0.22.2
            "8":
                - 3
            "10":
                - 21
            "12": 0.22.2
            "13": windows-amd64
learning_rate:
    value: 0.01
